version: '3.2'

services:
  mongo-trinca:
    image: mongo:4.2
    container_name: mongo-trinca
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: churras
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  churras-api:
    image: node:latest
    container_name: churras-api
    restart: always
    depends_on:
      - mongo-trinca
    ports:
      - ${PORT}:3333
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start:dev
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'
